version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node

  working_directory: ~/app

references:
  container_config: &circleci-commitlint
    docker:
      - image: williamlauze/circleci-commitlint:latest
    working_directory: /www

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  commitlint:
    <<: *circleci-commitlint
    steps:
      - checkout
      - run:
          name: commitlint
          command: |
            /bin/sh /.scripts/commitlint_range.sh

  checkout:
    <<: *defaults

    steps:
      - restore_cache:
          name: Restore Repository Cache
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - repo-{{ .Branch }}
            - repo-master
            - repo-

      - checkout

      - save_cache:
          name: Save Repository Cache
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

      - persist_to_workspace:
          root: .
          paths:
            - .

  install-dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore yarn Package Cache
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save yarn Package Cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Lint styles from SCSS files
          command: npx stylelint scss/*.scss -- --fix

      - run:
          name: Lint styles from Vue files
          command: npx stylelint src/components/*.vue -- --fix

      - run:
          name: Lint JS
          command: yarn lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Run tests
          command: yarn test:unit

  coverage:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Add Yarn Binary Folder To $PATH
          command: export PATH="$PATH:`yarn global bin`"

      - run:
          name: Generate and upload coverage report
          command: yarn test:unit --coverageDirectory=coverage

      - store_artifacts:
          path: coverage

  upload-coverage:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - codecov/upload:
          token: dca17109-8079-4335-b0ff-f0bf418672f6
          file: ~/app/coverage

workflows:
  version: 2

  main:
    jobs:
      - checkout
      - commitlint
      - install-dependencies:
          requires:
            - checkout
      - test:
          requires:
            - install-dependencies
      - coverage:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - upload-coverage:
          requires:
            - install-dependencies
            - test
            - coverage
            - lint